version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: mindspace
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    volumes:
      - mindspace-db:/var/lib/postgresql/data

  # neo4j:
  #   container_name: neo4j
  #   image: neo4j:latest
  #   restart: always
  #   environment:
  #     NEO4J_AUTH: neo4j/test1234
  #   ports:
  #     - '7474:7474'
  #     - '7687:7687'
  #   volumes:
  #     - ./neo4j/data:/data
  #     - ./neo4j/logs:/logs

  # backend:
  #   container_name: nest
  #   build:
  #     context: ./Mindspace_back
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/mindspace
  #   depends_on:
  #     - db

volumes:
  mindspace-db:
