version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    volumes:
      - ./:/var/lib/postgresql/data

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs

  backend:
    container_name: nest
    build:
      context: ./Mindspace_back
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '8000:8000'
    depends_on:
      - db
      - neo4j
